from snakemake.utils import min_version

min_version("7.25.0")


include: "rules/common.smk"
include: "rules/chewbacca.smk"
include: "rules/schema_prepare.smk"
include: "rules/assembly.smk"


wildcard_constraints:
    **get_constraints(),


rule all:
    input:
        **get_outputs(),
