chewbacca_schemas_dir: "/data/genome/others/cgmlst_schemas/chewbacca"
# here you can specify the directory where the schemas will be stored. If the directory does not exist, it will be created.

organism_schemas_mapping:
  - taxa_label: "klebsiella" # defines the name of output in results/
    GTDBtk_taxa: # specify taxa from GTDBtk taxonomy. Samples with this taxa will be used for this schema.
      - "Klebsiella pneumoniae"
      - "Klebsiella quasipneumoniae"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/ridom/Kpneumoniae2492"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Kpneumoniae2492/alleles/"
    # either provide custom schema in cgMLST_schema_dir or provide download URL to download the schema.
    # RIDOM schemas are at https://www.cgmlst.org/ncs/schema/ click on the organism of interest. Get the schema name from the URL as the last element.
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Klebsiella_pneumoniae.trn" # Training filename with extension.
    training_file_download_url: "https://github.com/B-UMMI/chewBBACA/raw/v3.3.8/CHEWBBACA/prodigal_training_files/Klebsiella_pneumoniae.trn"
    # If the file does not exist and valid URL is provided, it will be downloaded. Else file must be provided or error will be raised.

  - taxa_label: "nmeningitidis"
    GTDBtk_taxa:
      - "Neisseria meningitidis"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/custom/nmeningitidis_cgMLSTv3_20250319"
    cgMLST_schema_download_url: null # files created manually
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Neisseria_meningitidis_NCTC10025.trn"
    training_file_download_url: null # file provided manually

  - taxa_label: "bordetella"
    GTDBtk_taxa:
      - "Bordetella pertussis"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/ridom/Bpertussis2502"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Bpertussis2502/alleles/"
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/B_pertussis_NCBI_reference.trn"
    training_file_download_url: null # file provided manually, see workflow/resources

  - taxa_label: "campylobacter"
    GTDBtk_taxa:
      - "Campylobacter jejuni"
      - "Campylobacter coli"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/ridom/Cjejuni2496"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Cjejuni2496/alleles/"
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Campylobacter_jejuni.trn"
    training_file_download_url: "https://github.com/B-UMMI/chewBBACA/raw/v3.3.8/CHEWBBACA/prodigal_training_files/Campylobacter_jejuni.trn"

  - taxa_label: "senterica"
    GTDBtk_taxa:
      - "Salmonella enterica"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/ridom/Senterica2494"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Senterica2494/alleles/"
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Salmonella_enterica.trn"
    training_file_download_url: "https://github.com/B-UMMI/chewBBACA/raw/v3.3.8/CHEWBBACA/prodigal_training_files/Salmonella_enterica.trn"

  - taxa_label: "spneumoniae"
    GTDBtk_taxa:
      - "Streptococcus pneumoniae"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/custom/spneumoniae20240704"
    cgMLST_schema_download_url: null # constructed manually, see the path at GEN-MANAGER
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Streptococcus_pneumoniae.trn"
    training_file_download_url: "https://github.com/B-UMMI/chewBBACA/raw/v3.3.8/CHEWBBACA/prodigal_training_files/Streptococcus_pneumoniae.trn"

  - taxa_label: "efaecalis"
    GTDBtk_taxa:
      - "Enterococcus faecalis"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/ridom/Efaecalis2497"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Efaecalis2497/alleles/"
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Enterococcus_faecalis.trn"
    training_file_download_url: null # provided manually, see workflow/resources

  - taxa_label: "efaecium"
    GTDBtk_taxa:
      - "Enterococcus faecium"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/ridom/Efaecium2501"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Efaecium2501/alleles/"
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Enterococcus_faecium.trn"
    training_file_download_url: "https://github.com/B-UMMI/chewBBACA/raw/v3.3.8/CHEWBBACA/prodigal_training_files/Enterococcus_faecium.trn"

  - taxa_label: "ecoli"
    GTDBtk_taxa:
      - "Escherichia coli"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/ridom/Ecoli2489"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Ecoli2489/alleles/"
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Escherichia_coli.trn"
    training_file_download_url: "https://github.com/B-UMMI/chewBBACA/raw/v3.3.8/CHEWBBACA/prodigal_training_files/Escherichia_coli.trn"

  - taxa_label: "paeruginosa"
    GTDBtk_taxa:
      - "Pseudomonas aeruginosa"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/ridom/Paeruginosa2490"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Paeruginosa2490/alleles/"
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Pseudomonas_aeruginosa.trn"
    training_file_download_url: "https://github.com/B-UMMI/chewBBACA/raw/v3.3.8/CHEWBBACA/prodigal_training_files/Pseudomonas_aeruginosa.trn"

  - taxa_label: "saureus"
    GTDBtk_taxa:
      - "Staphylococcus aureus"
    cgMLST_schema_dir: "/data/genome/others/cgmlst_schemas/ridom/Saureus2490"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Saureus2490/alleles/"
    training_file_full_path: "/data/genome/others/cgmlst_schemas/training_files/Staphylococcus_aureus.trn"
    training_file_download_url: "https://github.com/B-UMMI/chewBBACA/raw/v3.3.8/CHEWBBACA/prodigal_training_files/Staphylococcus_aureus.trn"

max_threads: 28

threads:
  chewbacca: 28
