chewbacca_schemas_dir: "resources/schemas/chewbacca/"

organism_schemas_mapping:
  - taxa_label: "klebsiella" # defines the name of output in results/
    GTDBtk_taxa: # specify taxa from GTDBtk taxonomy. Samples with this taxa will be used for this schema.
      - "Klebsiella pneumoniae"
      - "Klebsiella quasipneumoniae"
    cgMLST_schema_dir: "resources/cgmlst_schemas/ridom/Kpneumoniae235"
    cgMLST_schema_download_url: "https://www.cgmlst.org/ncs/schema/Kpneumoniae235/alleles/"
    training_file_full_path: "resources/schemas/Klebsiella_pneumoniae.trn" # Training filename with extension. See files at https://github.com/B-UMMI/chewBBACA/blob/master/CHEWBBACA/prodigal_training_files/
    training_file_download_url: "https://github.com/B-UMMI/chewBBACA/raw/master/CHEWBBACA/prodigal_training_files/Klebsiella_pneumoniae.trn"

max_threads: 2

threads:
  chewbacca: 2

without_cgmlst_dist: False
